#+TITLE: To be learnt
#+SUBTITLE: 2nd Adults
#+AUTHOR: Nelson Lombardo
#+EMAIL: nelson.lombardo@gmail.com
#+DATE: 18th April 2021
#+KEYWORDS: English Week Adults
#+LANGUAGE: en
#+LATEX_HEADER: \usepackage[margin=0.75in]{geometry}
#+LATEX_HEADER: \usepackage[English]{babel}
#+LATEX_HEADER: \usepackage{soul,color}
#+LATEX_HEADER: \usepackage[table]{xcolor}
#+LATEX_HEADER: \setcounter{secnumdepth}{0}
#+OPTIONS: num:nil
#+HTML_HEAD: <link rel="shortcut icon" type="image/jpg" href="./img/favicon.png"/>
#+HTML_HEAD: <link rel="stylesheet" href="./css/org.css" type="text/css" />

* Books

  - Speakout Elementary 2nd Edition (Flexi Course Book 2)
  - MyGrammarLab Elementary A1/A2 (Pearson)
  - Reader: "The real McCoy and other ghots stories" Dominoes (One) (Oxford University Press)
  - Writing Booklet
  - Listening Booklet

* Travel Partners [unit 7.1]

** Comparatives: Rules

#+BEGIN_SRC dot :file ./img/u71_comparatives_rules.svg :cmdline -Kdot -Tsvg
  digraph { rankdir = LR; node [ style = "rounded, filled", fillcolor = "gray96", shape = box];
    "Short adjective" -> "fast" [ label = "as" ];
    "fast" -> "faster" [ label = "adjective + '-er'" ];
    "Long adjective" -> "comfortable" [ label = "as" ];
    "comfortable" -> "more comfortable" [ label = "'more' + adjective" ];
    "Irregular adjective" -> { "good", "bad" } [ label = "as" ];
    "good" -> "better"; "bad" -> "worse";
    { "better", "worse" } -> "than";
    { "faster", "more comfortable" }  -> "than";
  }
#+END_SRC

#+RESULTS:
[[file:./img/u71_comparatives_rules.svg]]
    
** Comparatives: Basic examples

    | Adjective   | Example                                                                |
    |-------------+------------------------------------------------------------------------|
    | nice        | Beach is _nicer_ than city for a day out.                              |
    | comfortable | Trainers are _more comfortable_ than shoes for travelling.             |
    | bad         | Travelling by bus is _worse_ than travelling by car on a hot day.      |
    | warm        | Madrid _is warmer than_ London.                                        |
    | expensive   | The Regal Hotel _is more expensive than_ Park Hotel.                   |
    | consume     | I the UK, coffee _is more consume than_ tea.                           |
    | near        | Heathrow Airport _is nearer to_ Central London _than_ Gatwick Airport. |
    | long        | The Toyota Prius _is longer than_ Toyota Auris.                        |
    | expensive   | Sunflowers by Van Gogh _is more expensive than_ Nympheas by Monet.     |

** Comparatives: More examples

    | Adjective   | Example                                                                              |
    |-------------+--------------------------------------------------------------------------------------|
    | tall        | My brother _is taller than_  me.                                                     |
    | young       | I'm eighteen but my best friend _is younger than_ me; she's seventeen.               |
    | nice        | Do you like Lucy? I think Mariela _is nicer than_ she.                               |
    | interesting | I don't like horror films; I think actions films  _are more interesting than_  them. |
    | rich        | Our neighbours _are richer than_ us.                                                 |
    | old         | My uncle is forty-five but my aunt _is older than_ he is.                            |

** Comparatives: Irregular adjectives

    | Adjective         | Comparative |
    |-------------------+-------------|
    | good              | better      |
    | well (healthy)    | better      |
    | bad               | worse       |
    | far               | further     |
    | old (people)      | elder       |

** Vocabulary: Adjectives

    | Adjective (Phonetics)            | Opposite      |
    |----------------------------------+---------------|
    | nice (/ nīs /)                   | ugly          |
    | hot (/ hät /)                    | cold          |
    | fast (/ fast/)                   | slow          |
    | crowded (/ ˈkroudəd /)           | empty         |
    | expensive (/ ikˈspensiv /)       | cheap         |
    | comfortable (/ ˈkəmfərdəb(ə)l /) | uncomfortable |
    | interesting (/ 'int(ə)rəstiNG /) | boring        |
    | quiet (/ ˈkwīət /)               | noisy         |

** Vocabulary: Places

   | Places            | Phonetics | Traduction             |
   |-------------------+-----------+------------------------|
   | a mountain        |           | una montaña            |
   | a hill            |           | una colina             |
   | a lake            |           | un lago                |
   | a forest          |           | un bosque              |
   | a village         |           | una villa              |
   | a market          |           | un mercado             |
   | a famous building |           | una edificación famosa |
   | a desert          |           | un desierto            |

** Vocabulary: Travel

#+BEGIN_SRC dot :file ./img/u71_travel.svg :cmdline -Kcirco -Tsvg
  digraph { rankdir = LR; node [ style = "rounded, filled", fillcolor = "gray96", shape = box]; overlap = false;
    "by" -> { "plane", "car", "train" };
    "in a" -> { "hotel", "self-catering apartment" };
    "go" -> { "sightseeing", "camping", "surfing", "horse riding", "shopping" };
    "go to" -> { "a café", "a nightclub", "a restaurant" };
    "be on" -> { "holiday" };
    "do" -> { "something" };
    "in" -> { "spring", "summer" };
  }
#+END_SRC

#+RESULTS:
[[file:travel.svg]]

** Vocabulary: Meanings

    | Adjective   | Definition                   |
    |-------------+------------------------------|
    | hot         | Having a high temperature    |
    | crowded     | Containing a lot of people   |
    | fast        | Quickly                      |
    | cheap       | Not expensive                |
    | noisy       | Making a lot of noise        |
    | cold        | Having a low temperature     |
    | comfortable | Feeling relaxed              |
    | interesting | Making you want to know more |

** Vocabulary: Phrases

   - 1) :: The train was _empty_, so there were lots of free places to sit.
   - 2) :: My computer is very _slow_ today. Everything is taking a long time.
   - 3) :: Don't sit in that chain. It's very _uncomfortable_.
   - 4) :: The lesson was so _boring_ that I fell asleep!
   - 5) :: Shh! Be _quiet_! There's an exam in that room.
   - 6) :: It's very _hot_ today. Would you like an ice cream?
   - 7) :: I really like it, but it's very _expensive_.
   - 8) :: The _fast_ train is more expensive, but much quicker.
   - 9) :: It's a great book, really _interesting_.
   - 10) :: The jacket was quiet _cheap_, it only cost a few euros.

* The longest bike ride [unit 7.2]
  
** Superlatives: Rules

#+BEGIN_SRC dot :file ./img/u72_superlatives_rules.svg :cmdline -Kdot -Tsvg
  digraph { rankdir = LR; node [ style = "rounded, filled", fillcolor = "gray96", shape = box];
    "Short adjective" -> "great" [ label = "as" ];
    "great" -> "the greatest" [ label = "'the' + adjective + '-est'"];
    "Long adjective" -> "exciting" [ label = "as" ];
    "exciting" -> "the most exciting" [ label = "'the most' + adjective "];
    "Irregular adjective" -> { "good", "bad" } [ label = "as" ];
    "good" -> "best"; "bad" -> "worst";
  }
#+END_SRC

#+RESULTS:
[[file:./img/u72_superlatives_rules.svg]]

** Superlatives: Examples

#+BEGIN_SRC dot :file ./img/u72_superlatives_examples.svg :cmdline -Kdot -Tsvg
  digraph { rankdir = LR; node [ style = "rounded, filled", fillcolor = "gray96", shape = box];
    "Which's the" -> "fastest" -> "way to travel?";
    "Which's the" -> "slowest" -> "way to get there?";
    "Which's the" -> { "most expensive", "cheapest" } -> "form to transport?";
    "Which's the" -> { "most comfortable" } -> "way to get there?";
    "Which's the" -> "best" -> "way to get to Ankara?";
    "Which's the" -> "worst" -> "restaurant in your town?";
    "What's the" -> "longest" -> "word in this sentence?";
    "What's the" -> "most difficult" -> "grammar in English?";
    "Who's the" -> "happiest" -> "person in your family?";
    "Who's the" -> "friendliest" -> "person in your English class?";
    "What was the" -> "coldest" -> "place you visited?";
  }
#+END_SRC

** Superlatives: Irregular adjectives

    | Adjective      | Comparative  |
    |----------------+--------------|
    | good           | the best     |
    | well (healthy) | the best     |
    | bad            | the worst    |
    | far            | the furthest |
    | old (people)   | the eldest   |
       
* Can you tell me the way? [unit 7.3]

** Function: Asking for and giving directions

    - Can / Could you tell me the way to ...?
    - How can I get to ...?
    - Is there a ... near here?
    - You can't miss it.
    - Let me think.

** Vocabulary: Places in the city

   | Place                      | Phonetics                       | Traduction                      |
   |----------------------------+---------------------------------+---------------------------------|
   | bus station                | / ˈbəs ˌstāSHən /               | estación de colectivos          |
   | theatre                    | /ˈθɪətə /                       | teatro                          |
   | car park                   | / kɑː pɑːk /                    | estacionamiento                 |
   | Tourist Information Office | / ˈtʊərɪst ˌɪnfəˈmeɪʃən ˈɒfɪs / | oficina de infomación turística |
   | museum                     | / mju(ː)ˈzɪəm /                 | museo                           |
   | art gallery                | / ɑːt ˈgæləri /                 | galería de arte                 |
   | park                       | / pɑːk /                        | parque                          |
   | square                     | / skweə  /                      | plaza                           |
   | swimming pool              | / ˈswɪmɪŋ puːl /                | pileta de natación              |
   | cinema                     | / ˈsɪnəmə /                     | cine                            |
   | post office                | / pəʊst ˈɒfɪs /                 | oficina postal                  |
   | school                     | / skuːl /                       | escuela                         |
   | bank                       | / bæŋk /                        | banco                           |
   | town hall                  | / taʊn hɔːl /                   | municipalidad                   |
   | sports centre              | / spɔːts ˈsɛntə  /              | centro de deportes              |

*** Vocabulary: Directions

     | Indications                           |
     |---------------------------------------|
     | go straight *go* / *ahead*            |
     | turn right / left                     |
     | go *up* / *down* / *along* (West St.) |
     | take the first / second / ...         |
     | take the next right / left            |
     | go *past* - *on* (the right - left)   |
     | opposite                              |
     | *on* the corner of ...                |
     | stop / turn ... at                    |

*** Vocabulary: Miscellaneous

     |                   |
     |-------------------|
     | pedestrian street |
     | traffic lights    |
     | crossroads        |
     | a corner          |
     | road              |

**** Common phrases

     - When you reach Holmes St.
     - ... until Holmes St.
     - ... Finally turn right / left
     - You can't miss it / Holmes St. is in front of you

* Hong Kong [unit 7.4]

** Vocabulary: General

   | Word             | Phonetics | Traduction                  |
   |------------------+-----------+-----------------------------|
   | skycraper        |           | rascacielos                 |
   | karaoke          |           | sitio o máquina para cantar |
   | tram             |           | tranvía                     |
   | shopping centre  |           | centro comercial            |
   | a bamboo steamer |           | una vaporera de bambú       |

** Vocabulary: Miscellaneous

   | Word           | Phonetics | Traduction |
   |----------------+-----------+------------|
   | challenges     |           |            |
   | rows           |           |            |
   | bamboo baskets |           |            |
   | a walk         |           |            |
   | street food    |           |            |
   | sites          |           |            |

** Vocabulary: Key phrases

#+BEGIN_SRC dot :file ./img/u74_vocabulary_key_phrases.svg :cmdline -Kdot -Tsvg
  digraph { rankdir = LR; node [ style = "rounded, filled", fillcolor = "gray96", shape = box];
    "It's in the" -> { "north", "south", "west", "east" } -> "of London.";
    "It's" -> "near ...";
      "It's" -> "next to ...";
    "There are lots of ...";
      "There are lots of" -> "some ...";
    "One of the most important places in ... is ...";
    "Most tourist don't know about it but...";
    "Here you can" -> { "see ...", "eat ...", "find ..." };
    "Tourists" -> { "don't usually", "often" } -> { "go there.", "do that." };
    "It's" -> { "the best", "one of the best", "a good" } -> { "place ", "places" } -> "you can ... there.";
      { "place ", "places" } -> "to ...";
    "It's really" -> { "interesting ...", "delicious ...", "fun ...", "quiet ...", "beaufiul ..." };
 }
#+END_SRC

* Having a great time [unit 8.1]

** Present continuous: Rules positives / negatives

#+BEGIN_SRC dot :file ./img/u81_present_continuous_rules_positive_negative.svg :cmdline -Kdot -Tsvg
  digraph { rankdir = LR; node [ style = "rounded, filled", fillcolor = "gray96", shape = box];
    "I" -> "am / 'm" -> "watching TV.";
    "I" -> "am not / 'm not" -> "watching TV.";
    "He / She / It" -> "is / 's" -> "watching TV.";
    "He / She / It" -> "is not / 's not" -> "watching TV.";
    "We / You / They" -> "are / 're" -> "watching TV.";
    "We / You / They" -> "are not / 're not" -> "watching TV.";
  }
#+END_SRC

** Present continuous: Rules for questions

#+BEGIN_SRC dot :file ./img/u81_present_continuous_questions_yesno.svg :cmdline -Kdot -Tsvg
  digraph { rankdir = LR; node [ style = "rounded, filled", fillcolor = "gray96", shape = box];
    "Am" -> "I" -> "sitting here?";
    "Is" -> "he / she / it" -> "sitting here?";
    "Are" -> "we / you / they" -> "sitting here?";
  }
#+END_SRC

#+BEGIN_SRC dot :file ./img/u81_present_continuous_questions_wh_element.svg :cmdline -Kdot -Tsvg
  digraph { rankdir = LR; node [ style = "rounded, filled", fillcolor = "gray96", shape = box];
    "What" -> "am" -> "I" -> "doing?";
    "Where" -> "is" -> "he / she / it"-> "going?";
    "Why" -> "are" -> "we / you / they" -> "running?";
  }
#+END_SRC

#+RESULTS:
[[file:./img/u81_present_continuous_questions_wh_element.svg]]

    In questions, we put /am/is/are/ before the subject of the sentence. Whe put the /-ing/ from after the subject:

    - What *are* you *studying* this term?
    - *Is* she *listening* to the radio?
    - +*Are* *waiting* you for me?+
    - +*Waiting* *are* you for me?+
    - *Are* you *waiting* for me?

    We don't usually repeat the main verb when we answer questions:

    - Is that man *phoning* the police?
      - +Yes, he is phoning.+ Yes, he is.
      - +No, he isn't phoning.+ No, he isn't.

    We don't use the short form of the verb in short answers with yes.

    - Is she sleeping?
      - +Yes, she's.+ Yes, she is.

** Present coninuous: Forms

   | + -ing    | double consonante + -ing | (-e) + -ing |
   |-----------+--------------------------+-------------|
   | happening | running                  | living      |
   | sleeping  | sitting                  | making      |
   | visiting  | stopping                 | taking      |
   | waiting   | swimming                 | using       |


** Present continuous: Use

   We use the present continuous

   - to describe something that is happening while we are speaking.
   - to talk about something that is happening around now, for a limited period of time.

   We often use time expressions (e.g. rigth now, now, at the moment, today, this week).

   We often use the present coninuous to talk about what is happening in pictures and photos:

   - What *are* they *doing*?
     - They're *watching* a film.
   - That's an interesting painting. *Is* that woman *writing* something?
     - No, she isn't. She's *reading* a letter

** Present continuous: Basic examples

   | Hurry up. The taxi's _waiting_ outside right now.                      |
   | Can you help me? I'm _looking_ for the post office.                    |
   | James can't come to the door - he's _having_ a bath.                   |
   | I'm using my brother's computer today because mine isn't _working_.    |
   | We're on holiday this week. We're _staying_ in a hotel near the beach. |
   | This year we're _studying_ the history of the theatre.                 |
   | Susy's _running_ in the park.                                          |
   | They're _relaxing_ in the garden.                                      |
   | Jenny's _making_ a cake.                                               |
   | The children are _sitting_ on the sofa.                                |
   | Pedro is _swiming_ in a river.                                         |
   | They are _waiting_ for a bus.                                          |

** Present continuous: More examples

   | Fernando can't come to the phone because he _is having_ a shower.               |
   | It's cold today so I _am wearing_ a pullover.                                   |
   | Jane's cooker isn't working so she _is eating_ in a restaurant today.           |
   | The weather is nice today so the children _are playing_ in the garden.          |
   | Dave can't send you an email because his computer _is not working_.             |
   | Carla has hurt her leg so she _is not dancing at the moment.                    |
   | Hurry up! It's time to leave. The taxi _is waiting_ outside.                    |
   | We have a lot of work in the office today so we _aren't having_ a launch break. |
   | It's a bank holiday so most people _aren't going_ to work today.                |

* What a difference! [unit 8.2]

** Appearence, clothes and parts of face

#+BEGIN_SRC dot :file ./img/u82_appearence :cmdline -Kcirco -Tsvg
  digraph { rankdir = LR; node [ style = "rounded, filled", fillcolor = "gray96", shape = box];
    "tall" -> "short" [ dir = both ];
    "slim" -> "overweight" [ dir = both ];
  }
#+END_SRC

#+RESULTS:
[[file:./img/u82_appearence]]

  | Clothes               | Phonetics  | Traducción    |
  |-----------------------+------------+---------------|
  | socks                 |            | medias        |
  | jeans                 |            | vaqueros      |
  | suit                  | / sut /    | traje         |
  | jacket                | / shaket / | chaqueta      |
  | trousers              |            | pantalones    |
  | shirt                 |            | camisa        |
  | tie                   |            | corbata       |
  | top                   |            | +top+         |
  | skirt                 |            | falda         |
  | sweater               |            | +sweater+     |
  | shorts                |            | +shorts+      |
  | dress                 |            | vestido       |
  | T-shirt               |            | remera        |
  | coat                  |            | abrigo        |
  | sunglasses            |            | lentes de sol |
  | trainers              |            | zapatillas    |
  | boots                 | / buts /   | botas         |
  | sandals               |            | sandalias     |
  | shoes                 |            | zapatos       |
  | casual/formal clothes |            |               |
  | underwear             |            | ropa interior |

* What do you recommend? [unit 8.3]

** Function: Asking recomendations

*** Key Phrases

#+BEGIN_SRC dot :file ./img/u83_key_phrases.svg :cmdline -Kdot -Tsvg
  digraph { rankdir = LR; node [ style = "rounded, filled", fillcolor = "gray96", shape = box]; overlap = false;
    "¿Me podés recomendar una buena película?" -> "Can you recommend a good film?";
    "Dejame pensar..." -> "Let me think...";
    "¿Qué tipo de películas te gustan?" -> "What kind of films do you like?";
    "¿Qué hay de Gravity?" -> { "How about Gravity?", "What about Gravity?" };
    "¿De qué se trata?" -> { "What is it about?" };
    "¿Quién actua?" -> "Who is in it?";
    "Creo que te puede gustar.\nEs muy interesante - emocionante -\ngraciosa - entretenida - amorosa - movilizadora..." -> "I think you'd like it.\nIt's very interesting - exciting -\nfunny - entertaining - lovely - moving...";
    "¡Suena genial!" -> "Sounds good!";
    "Hay una buena película llamada..." -> "There's a good film called...";
    "El actor principal es..." -> "The main actor is...";
    "La actriz principal es..." -> "The main actress is...";
  }
#+END_SRC

#+RESULTS:
[[file:./img/u83_key_phrases.svg]]

** Vocabulary

*** Types of films
    
#+BEGIN_SRC dot :file ./img/u83_vocabulary.svg :cmdline -Kcirco -Tsvg
  digraph { rankdir = LR; node [ style = "rounded, filled", fillcolor = "gray96", shape = box]; overlap = false;
    "película romántica" -> "romantic film";
    "película de terror" -> "horror film";
    "drama" -> "drama";
    "musical" -> "musical";
    "película de acción" -> "action film";
    "comedia" -> "comedy";
    "película de ciencia ficción" -> "sci-fi film";
    "película de animación" -> "animation film";
    "suspenso" -> "thriller";
    "película de fantasía" -> "fantasy film";
    "película histórica" -> "historical film";
  }
#+END_SRC

#+RESULTS:
[[file:./img/u8_vocabulary.svg]]

*** Examples

#+BEGIN_SRC dot :file ./img/u83_examples.svg :cmdline -Kdot -Tsvg
  digraph { rankdir = LR; node [ style = "rounded, filled", fillcolor = "gray96", shape = box]; overlap = false;
    subgraph {
      "Noventa minutos en el mundo
      aterrador de vampiros y sangre..."
        -> "Ninety minutes in the scary
           world of vampires and blood..."
        -> "Horror film";
    }
    subgraph {
      "Los amigos de la infancia Jésica y Tim
      se reunen luego de diez años, y ellos
      buscan ser algo más que sólo buenos amigos..."
        -> "Childhood friends Jessica and Tim
           meet after ten years, and they want
           to be more than just good friends..."
        -> "Romantic";
    }
    subgraph {
      "Gene Walker is un Fred Astaire moderno,
      bailando y cantando por las calles de Cordoba..."
        -> "Gene Walker is a modern-day Fred Astaire,
           dancing and singing his way through the
           streets of Cordoba..."
        -> "Musical";
    }
    subgraph {
      "El oficial de policia de New York Jack Hare
      se toma unas vacaciones en Miami, pero termina
      trabajando para salvar el país de un ataque terrorista..."
        -> "New York police officer Jack Hare takes a holiday
           in Miami, but finds himself working to save the
           country from a terrorist attack."
        -> "Action film";
    }
    subgraph {
      "Un granjero en Francia despierta y descrubre que todos
      sus aniamles pueden hablar... Chino. Muchas risas mientras
      los granjeros aprenden Chino para hablar con los animales..."
        -> "A farmer in France wakes up and finds that all
           his animals can speak... Chinese. Lots of laughs as
           the farmers teaches himself Chinese to talk to the animals..."
        -> "Comedy";
    }
    subgraph {
      "Una pequeña villa India tiene visitas de turistas del espacio -
      extraterrestres de otra galaxy. Una sorpresa como los extraterrestres
      tienen más que aprender de los lugareños de lo que piensan..."
        -> "A small Indian village has a visit from space tourists -
           aliens from another galaxy. A surprise as the aliens have
           more to learn from the locals than they think..."
        -> "Sci-Fi film";
    }
    subgraph {
      "Sally Bonner pierde a sus padres en un accidente de tren.
      Ella es ciega y crece sola sin amigos... pero entonces
      Edmund, su profesor, ayuda a Sally a tocar el piano..." 
      -> "Sally Bonner loses her parents in a train accident.
         She is blind and grows up alone with no friends...
         but then Edmund, her teacher, helps Sally learn to
         play the piano..."
      -> "Drama"
    }
  }
#+END_SRC

*** Conversation

    | Person A                                      | Person B                                                    |
    |-----------------------------------------------+-------------------------------------------------------------|
    | Do you want to watch a film?                  | Sorry, I'm busy                                             |
    | Oh. Well then, can you recommend a good film? | Hmm... What kind of films do you like                       |
    | Horror films, action films...                 | Do you like sci-fi?                                         |
    | I don't know many sci-fi films.               | How about The Hunger Games? Do you know it?                 |
    | What's about it?                              | It's about the future and the way rich people control us... |
    | Who's in it?                                  | Jennifer Lawrence and Josh Hutcherson.                      |
    | Oh, she's good                                | Yeah. It's a good film - I think you'd like it              |
    
* Changing trends [unit 8.4]

** Function

*** Key phrases

#+BEGIN_SRC dot :file ./img/u84_key_phrases.svg :cmdline -Kdot -Tsvg
  digraph { rankdir = LR; node [ style = "rounded, filled", fillcolor = "gray96", shape = box]; overlap = false;
    "¿Te puedo hacer algunas preguntas?" -> "Can I ask you a few questions?";
    "¿Qué tipo de festival te gustan?" -> "What kind of festival do you like?";
    "A las personas le gusta porque..." -> "People like it because...";
    "Esto depende del festival..." -> "It depends on the festival...";
    "Hace años no podías conseguir\ninformación de internet" -> "Years ago you couldn't always\nget information on the internet.";
    subgraph {
      "¿Cómo es diferente ahora?" -> "How is it different now?";
      "¿En que se diferencia de antes?" -> "How is it different from before?";
      "¿En qué se diferencian ahora?" -> "How are they different now?";
      "¿En qué se diferencian de antes?" -> "How are they differente from before?";
    }
    subgraph {
      "Esto es muy popular en este momento." -> "It's very popular at the moment.";
      "Ellos son muy populares en este momento." -> "They're very popular at the moment.";
    }
    subgraph {
      "La seguridad es mucho mejor que antes." -> "Security is much better than before";
      "Los precios son mucho más caros que antes." -> "Prices are more expensive than before";
      "Los precios son mucho más baratos que antes." -> "Prices are cheaper than before";
    }
  }
#+END_SRC

#+RESULTS:
[[file:./img/u84_key_phrases.svg]]

** Vocabulary

#+BEGIN_SRC dot :file ./img/u84_vocabulary.svg :cmdline -Kcirco -Tsvg
  digraph { rankdir = LR; node [ style = "rounded, filled", fillcolor = "gray96", shape = box]; overlap = false;
    "compra en línea" -> "shopping online";
    "comprando en una pequeña tienda" -> "shopping in a small shop";
    "compras en grandes centros comerciales" -> "shopping in a big shopping malls";
    "compras en un gran centro comercial" -> "shopping in a big shopping centre";
    "conveniencia" -> "convenience";
    "conveniente" -> "convenient";
    "disfrute" -> "enjoyment";
    "tendencias" -> "trends";
    "hipermercados" -> "hypermarkets";
    "en comparación con" -> "compared to";
    "sala de exposición" -> "showroom";
    "compradores" -> "shoppers";
    "la misma que (ahora)" -> "the same as (now)";
    "una tienda departamental" -> "a department store";
  }
#+END_SRC

#+RESULTS:
[[file:./img/u84_vocabulary.svg]]

* Citybikes [unit 9.1]

** Grammar

*** Functions

#+BEGIN_SRC dot :file ./img/u91_grammar.svg :cmdline -Kcirco -Tsvg
  digraph { rankdir = LR; node [ style = "rounded, filled", fillcolor = "gray96", shape = box]; overlap = false;
    subgraph {
      "Poder" -> "Can";
      "No poder" -> "Can't";
    }
    subgraph {
      "Tener que" -> "Have to";
      "No tener que" -> "Don't have to";
    }
  }
#+END_SRC

#+RESULTS:
[[file:./img/u91_grammar.svg]]

*** Examples
    
   - 1) :: Motorbikes _can't go_ here. They _have to_ go on another road.
   - 2) :: You _can_ park here for free. You _don't have to_ pay for fifteen minutes' parking.
   - 3) :: Bikes _have to_ keep left. People on foot _can't_ walk on the left.
   - 4) :: You _can_ catch the bus here. You _don't have to_ wait more than ten minutes.
   - 5) :: You _can't_ ride your bike. You _have to_ get off and walk.
   - 6) :: You _can_ take a taxi here. You _can't_ park here.

*** Conversations

   - A) :: You _have to wear_ a jacket and tie to this dinner. It's very formal party.
   - B) :: But it's so hot!
   - A) :: Well, you _can wear_ your light jacket.

   - A) :: You _don't have to come_ to the meeting. It's not very important.
   - B) :: That's good because I _can't come_ - I'm too busy.

   - A) :: I _have to get_ a birthday present to Sandra. I completely forgot yesterday.
   - B) :: It's OK. You _don't have to get_ anything. I bought her a present from both of us.
   - A) :: Thanks! What did you buy?

** Vocabulary

*** Adjectives to describe transport

#+BEGIN_SRC dot :file ./img/u91_vocabulary.svg :cmdline -Kcirco -Tsvg
  digraph { rankdir = LR; node [ style = "rounded, filled", fillcolor = "gray96", shape = box]; overlap = false;
    "conveniente" -> "convenient";
    "inconveniente" -> "inconvenient";
    "saludable" -> "healthy";
    "no saludable" -> "unhealthy";
    "lento" -> "slow";
    "rápido" -> "fast";
    "contaminadora" -> "polluting";
    "amigable con el ambiente" -> "green";
    "seguro" -> "safe";
    "difícil" -> "difficult";
    "fácil" -> "easy";
    "peligroso" -> "dangerous";
    "cómodo" -> "comfortable";
    "incómodo" -> "uncomfortable";
    "exitoso" -> "successful";
    "fracaso" -> "unsuccessful";
    "casco" -> "helmet";
    "cinturón de seguridad" -> "seatbelt";
  }
#+END_SRC
   
* Vocabulary: Adjectives examples

   | Adjective   | Traduction  | Sentences                                               |
   |-------------+-------------+---------------------------------------------------------|
   | angry       | enojado     | Is everything ok? You look _angry_.                     |
   | bored       | aburrido    | I'd be so _bored_ if I didn't have wi-fi.               |
   | embarrassed | avergonzado | You shouldn't feel _embarrassed_ about your English.    |
   | excited     |             | I'm super _excited_ about my trip to Cambridge.         |
   | happy       | feliz       | Congratulations, I'm so _happy_ for you.                |
   | sad         | triste      | We're really _sad_ to see you go.                       |
   | hungry      | hambriento  | If you're _hungry_, help yourself to a sandwich.        |
   | thirsty     | sediento    | You must be _thirsty_ after your gym session!           |
   | tired       | cansado     | I'm pretty _tired_ so I'm going to take a nap.          |
   | sleepy      | somnoliento | The sound of your voice makes me _sleepy_.              |
   | upset       | enojado     | Laura is _upset_ because I forgot to call her.          |
   | grateful    | agradecido  | I'm incredigly _grateful_ for all your support.         |
   | amused      | entretenido | The teacher was not _amused_ by my joke.                |
   | outraged    | indignado   | I'm _outraged_ by your lack of professionalism.         |
   | annoyed     | irritado    | I'm pretty _annoyed_ that you didn't tell me the truth. |
   | anxious     | ansioso     | If you're feeling _anxious_, go for a long walk.        |


** Wh - questions

*** Examples

    Wh- questions *always* start with a wh- word

    | who | what | when | where | how | which | why | whose |

    Practice

    | How can | How many | What can | Where can | Why is | Why should |

    - 0) :: _Why should_ I buy the *Generation X* DVD recorder?
    That's simple - because it's the most modern and best new DVD recorder!
    - 1) :: _Why is_ the *Generation X* recorder more expensive than most of the others?
    Well, it's only a little more expensive... and it is better than most others, for example, it can store more films.
    - 2) :: _How many_ films can the *Generation X* recorder store?
    About 100. It depends on how long the films are.
    - 3) :: _How can_ I use my old videos with this machine?
    If you

**** Make questions from the statements.

     - 0) :: I'm not sure where the nearest bank is. _Where is the nearest bank?_
     - 1) :: I'm not sure where we're staying. _Where are we staying?_
     - 2) :: I'm not sure how we get to the station. _How do we get to the station?_
     - 3) :: I'm not sure what time the plane arrived. _What time did the plane arrive?_
     - 4) :: I'm not sure what kind of computer she wants. _What kind of computer does she want?_
     - 5) :: You didn't phone me. I don't know why. _Why didn't phone you phone me?_
     - 6) :: I'm not sure which class I'm in. _Which class am I in?_

**** Complete the job interview with questions. Use the words in brackets

     - A) :: Right. Do you have any questions about the job?
     - B) :: Yes, I do, actually. _What time do you start_ in the morning?
     - A) :: We open at 9.30 and the assistants have to be here at 9.00 or 8.30 on Thurdays.
